In [16]:
#Methods of Strings
S="Kharagpur"


print(S.count("a"))
print(S.find("g"))
print(S.casefold())
print(S.capitalize())
print(S.islower())

2
5
kharagpur
Kharagpur
False

In [27]:
#Methods of List
L=[89,56,52,34,56,78,989,232,43,56]
L.append(23)
print(L)
print(L.count(56))
L.insert(5,33)
print(L)
L.remove(78)
print(L)
L.sort()
print(L)

[89, 56, 52, 34, 56, 78, 989, 232, 43, 56, 23]
3
[89, 56, 52, 34, 56, 33, 78, 989, 232, 43, 56, 23]
[89, 56, 52, 34, 56, 33, 989, 232, 43, 56, 23]
[23, 33, 34, 43, 52, 56, 56, 56, 89, 232, 989]

In [36]:
#methods of Tuples
T=("egg","bread","butter","music","jam","egg")
print(T)
print(type(T))
print(len(T))
print(T[3])
print(T.count("egg"))
print(T.index("jam"))

('egg', 'bread', 'butter', 'music', 'jam', 'egg')
<class 'tuple'>
6
music
2
4

In [43]:
#methods of set

X={1,3,651,75,3445,345,45,2,3,3,3,3}
Y={3,75,45,234,54,345,323,898}
print(X)
X.add(90)
print(X)
Z=set.difference(X,Y)
print(Z)
Z=set.intersection(X,Y)
print(Z)
Z=set.union(X,Y)
print(Z)

{1, 2, 3, 75, 651, 45, 3445, 345}
{1, 2, 3, 75, 651, 45, 3445, 345, 90}
{1, 2, 651, 3445, 90}
{345, 75, 3, 45}
{1, 2, 3, 898, 323, 234, 75, 651, 45, 3445, 54, 345, 90}

In [49]:
#method of dictionaries

D = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print(D.items())
print(D.keys())
print(D.get("brand"))
print(D.fromkeys("year"))
print(D.values())

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])
dict_keys(['brand', 'model', 'year'])
Ford
{'y': None, 'e': None, 'a': None, 'r': None}
dict_values(['Ford', 'Mustang', 1964])

In [53]:
#arithmaetic operators
a=867
b=9856
print(a+b)
print(a-b)
print(a*b)
print(b**a)
print(a/b)
print(b//a)
print(b%a)

10723
-8989
8545152
3455432464697273895888174567164700814511516570996360199014855287704379427597812381048224448692842861138209556282246417138328947280891931911371840877287134726399824997329362477594304724901700188102162798466637517586850137450611677472024772709246370429033492654716465864399627830141400263328288604488717800934236966662836146001417133094938583930859146233662921062584186398617639019789298157320810135099752718821722337337237634253896519609475903892893151904639001487107661456284377507382479664336143206298140242093174962154749578815814083552168626011882068245677172442335649729233061242954827887258270952324630465750904420119833222487364036623568858762175545549748134542177567526081140314757025891955625897094535145600714519536802850480016522975284326085622559015089789691359372455081417086347371344882056140153087274442090158511971083979968885857158303343156819224795154710793710380423134687888634143947996268467600235123636136268093872992607427447938684384543666081939722411589794194766813273579164118405961146588811633598857777308421284136499496893355345462254077882642003759555869875038612818883846388877206973833835520648981125137240854782007858995058802317097979466985203939741383617152796927348992684831543336817833160227890467813936428795860797702983306663883933883562814918748863833504627938886367960755867756638594618541205387897012596406642468168853753019131925765097643295449470140432209293198105623056282048720127181303093467191492575722042557849870242769761518321324818567455830939574849069327062947916906200492504144816091488167906751517834945383046827425873696559785374332921039789050068348289196746582532725327749442951383071938675916470286542747986374607326940339399200760312902322090993064138127952754201763321903283676823546539599773616405711435961542062749293160017917742172523259524496832536543544241097665543387837654560432304305335878274811131755962030487659540632388911664632496392150300726219939499791249133608226638236277522003867422334274955008583310319419907710091621006575703557740073572898703480619171980355288006581752103494732613758878033330518963273249794444426241905580737105340630984104866672646902870838114422306780408710046651095439302566965060465500993861116408098106450975034816139946959101402738430580519801550997840048455871537390706127028391003837555121031818522695247737158577832881217281260226569656871243163247206767845685362652270656855817971555721292527110686177808495846569648275222043848834453013401790467619170675947227104988019508333064487285433368419090863552666986878772015377082796937556372457063562750324643548732301580882756262708058281061727126588979922752829800589419050817009949179017361752274980941959277045967732499514691021805961577282793503985625372454269082520032079133604447600637125836433052986503389203350970678866120617131334029667851394923406560686140359758837166170888056159926407380396468643686981757118703938861740560862011847702520007577453273188703788027840529808774364296068675108911944929264062923256639404346562159454297356029008703548595578281606520283751190422611732920298651574246068076772273738603061246473854754799293284242688396849605755373288231004411352157204842224480174228859574013702511329710245747151861291433570628030362214853677073332366750709781931051481904691297620484459751470939308900646412330854428431403749401453410794764923074424489738627454302016504171835416224262240790892013874779542344449477664383075283696369748244759572169699977266980847823467499686281856679936
0.08796672077922078
11
319